server {
	listen 127.0.0.1:8080;
	root /data;
	client_max_body_size 5M; #The same as 5MB
	
	error_page 400 /error_pages/400.html;
	error_page 403 /error_pages/403.html;
	error_page 404 /error_pages/404.html;
	error_page 405 /error_pages/405.html;
	error_page 413 /error_pages/413.html;
	error_page 500 /error_pages/500.html;
	error_page 502 /error_pages/502.html;

	location /concerts {
		return = 301 https://www.youtube.com/watch?v=4rgSzQwe5DQ&list=PLcGkkXtask_e9vGe0O0DCGcr5EC5v3SYc; #301 is the HTTP status code for "Moved Permanently"
	}

	location /{
		root /data;
		index /html/index.html;
		allowed_methods GET POST;
		upload_store /upload; #work if relative path
		autoindex on; 
        
    }

# 	# CGI Handler
	location /cgi-bin {
		root /data;
		cgi_pass .py /usr/bin/python3;
		allowed_methods GET POST DELETE;
		autoindex off;
	}

	location /images {
		root  /data/images;
		index  index.html;
		allowed_methods  GET;
		autoindex off;
	}

	location /upload {
		root  /data/upload;
		index index.html;
		allowed_methods  GET POST DELETE;
		autoindex off; 
	}

}

server {
	listen 127.0.0.1:8082;
	client_max_body_size  50000;

    location /{
		root  /data/web2;
		index  index.html .html;
		allowed_methods  GET POST DELETE;
		autoindex  off;
	}
}

# server {
# 	listen 127.0.0.1:8081;
# 	client_max_body_size  100;
# 	root /YoupiBanane;

#     location /{
# 		root  /YoupiBanane;
# 		index  youpi.bla;
# 		allowed_methods  GET;
# 		autoindex  off; #Enables directory listing - We can turn this on and off as much as we want. (It shows the files in the directory)
#     }

# 	location /youpi.bla{
# 		cgi_pass .py /usr/bin/python3;
# 		allowed_methods POST;
# 	}

# 	location /post_body {
# 		allowed_methods POST;
# 	}

# 	location /directory/ {
# 		allowed_methods GET;
# 		index youpi.bad_extension;
# 	}
# }
