server {
	listen 127.0.0.1:8080;
	root /data/;
	#no server_name. / Fallback server block.
	client_max_body_size 5M; #The same as 5MB
	# Error pages
	error_page 400 /error_pages/400.html;
	error_page 403 /error_pages/403.html;
	error_page 404 /error_pages/404.html;
	error_page 405 /error_pages/405.html;
	error_page 413 /error_pages/413.html;
	error_page 500 /error_pages/500.html;
	error_page 502 /error_pages/502.html;

	#Serving Static Content // redirection return html code 3xx url/uri
	# location /redirect_html {
	# 	return = 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ ; #301 is the HTTP status code for "Moved Permanently"
	# }

	# Root Handler (Homepage)
	location /{
		root /data/html;
		index .html;
		allowed_methods GET POST DELETE;
		autoindex off; #Enables directory listing - We can turn this on and off as much as we want. (It shows the files in the directory)
        # return = 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ ; #301 is the HTTP status code for "Moved Permanently"
    }

	# CGI Handler
	location /cgi-bin {
		root /data;
		allowed_methods GET POST DELETE;
		autoindex off; # if it is on, it still forbidden access
	}

	location /images {
		root  /data;
		index  index.html;
		allowed_methods  GET;
		autoindex on; #Enables directory listing - We can turn this on and off as much as we want. (It shows the files in the directory)
	}

}

server {
	# host = localhost;
	listen = 4242;
	server_name = website.com; #Optional definition.
	client_max_body_size = 5000000;

	# Error pages
	error_page 400 = /error_pages/400.html;
	error_page 403 = /error_pages/403.html;
	error_page 404 = /error_pages/404.html;
	error_page 413 = /error_pages/413.html;
	error_page 500 = /error_pages/500.html;
	error_page 502 = /error_pages/502.html;

    location /{
		root = /data/root2/;
		index = .html;
		allowed_methods = GET POST DELETE;
		autoindex = off; #Enables directory listing - We can turn this on and off as much as we want. (It shows the files in the directory)
    }
}
