# =============================================================================
# WEBSERV CONFIGURATION FILE
# =============================================================================

server {
	# listen 127.0.0.1:8080;
	# root /data;
	# client_max_body_size 5M;

	# location / {
	# 	root /data;
	# 	index /html/index.html;
	# 	allowed_methods GET POST;
	# 	autoindex on;
	# }
}
