# =============================================================================
# WEBSERV CONFIGURATION FILE
# =============================================================================

server {
	listen 127.0.0.1:8080;
	root /data;
	client_max_body_size 5M;

	location / {
		root /data;
		index /html/index.html;
		allowed_methods GET POST;
		upload_store /upload;
		autoindex on;
	}
}

server {
	listen 127.0.0.1:8081;
	root /YoupiBanane;
	client_max_body_size 100;

	location / {
		root /YoupiBanane;
		index youpi.bla;
		allowed_methods GET POST;
		autoindex off;
	}
}

server {
	listen 127.0.0.1:8082;
	client_max_body_size 50000;

	location / {
		root /data/web2;
		index index.html;
		allowed_methods GET POST DELETE;
		autoindex off;
	}
}

server {
	listen 127.0.0.1:9090;
	root /data/admin;
	client_max_body_size 100M;

	location /files {
		root /data/admin/files;
		allowed_methods GET POST DELETE;
		upload_store /data/admin/files;
		autoindex on;
	}
}

server {
	listen 127.0.0.1:8888;
	root /data/static;
	client_max_body_size 1M;

	location /assets {
		root /data/static/assets;
		allowed_methods GET;
		autoindex on;
	}
}